id: PYSEC-0000-CVE-2013-4259
package:
  name: ansible
  ecosystem: PyPI
details: runner/connection_plugins/ssh.py in Ansible before 1.2.3, when using ControlPersist,
  allows local users to redirect a ssh session via a symlink attack on a socket file
  with a predictable name in /tmp/.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.2.3
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=998223
- type: WEB
  url: http://www.ansible.com/security
- type: WEB
  url: https://groups.google.com/forum/#!topic/ansible-project/UVDYW0HGcNg
aliases:
- CVE-2013-4259
modified: "2018-10-30T16:28:00Z"
published: "2013-09-16T19:14:00Z"
