id: PYSEC-0000-CVE-2017-7466
package:
  name: ansible
  ecosystem: PyPI
details: Ansible before version 2.3 has an input validation vulnerability in the handling
  of data sent from client systems. An attacker with control over a client system
  being managed by Ansible, and the ability to send facts back to the Ansible server,
  could use this flaw to execute arbitrary code on the Ansible server using the Ansible
  server privileges.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.3.0.0
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2017-7466
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1685
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1599
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1499
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1476
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1334
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1244
- type: WEB
  url: http://www.securityfocus.com/bid/97595
aliases:
- CVE-2017-7466
modified: "2019-10-09T23:29:00Z"
published: "2018-06-22T13:29:00Z"
