id: PYSEC-0000-CVE-2019-14856
package:
  name: ansible
  ecosystem: PyPI
details: ansible before versions 2.8.6, 2.7.14, 2.6.20 is vulnerable to a None
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: 2.6.0
    fixed: 2.6.20
  - type: ECOSYSTEM
    introduced: 2.7.0
    fixed: 2.7.14
  - type: ECOSYSTEM
    introduced: 2.8.0
    fixed: 2.8.6
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14856
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2020:0756
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html
aliases:
- CVE-2019-14856
modified: "2020-12-04T18:15:00Z"
published: "2019-11-26T14:15:00Z"
