id: PYSEC-0000-CVE-2014-4658
package:
  name: ansible
  ecosystem: PyPI
details: The vault subsystem in Ansible before 1.5.5 does not set the umask before
  creation or modification of a vault file, which allows local users to obtain sensitive
  key information by reading a file.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.5.5
references:
- type: WEB
  url: https://www.securityfocus.com/bid/68233
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
aliases:
- CVE-2014-4658
modified: "2020-02-25T20:19:00Z"
published: "2020-02-20T15:15:00Z"
