id: PYSEC-0000-CVE-2014-4966
package:
  name: ansible
  ecosystem: PyPI
details: Ansible before 1.6.7 does not prevent inventory data with "{{" and "lookup"
  substrings, and does not prevent remote data with "{{" substrings, which allows
  remote attackers to execute arbitrary code via (1) crafted lookup('pipe') calls
  or (2) crafted Jinja2 data.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    fixed: 62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
  - type: ECOSYSTEM
    fixed: 1.6.7
references:
- type: WEB
  url: https://github.com/ansible/ansible/commit/62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
- type: WEB
  url: http://www.ocert.org/advisories/ocert-2014-004.html
aliases:
- CVE-2014-4966
modified: "2020-02-26T14:40:00Z"
published: "2020-02-18T15:15:00Z"
