id: PYSEC-0000-CVE-2020-10729
package:
  name: ansible
  ecosystem: PyPI
details: A flaw was found in the use of insufficiently random values in Ansible. Two
  random password lookups of the same length generate the equal value as the template
  caching action for the same file since no re-evaluation happens. The highest threat
  from this vulnerability would be that all passwords are exposed at once for the
  file. This flaw affects Ansible Engine versions before 2.9.6.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.9.6
references:
- type: WEB
  url: https://github.com/ansible/ansible/issues/34144
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=1831089
aliases:
- CVE-2020-10729
modified: "2021-06-07T18:44:00Z"
published: "2021-05-27T19:15:00Z"
