id: PYSEC-0000-CVE-2014-2686
package:
  name: ansible
  ecosystem: PyPI
details: Ansible prior to 1.5.4 mishandles the evaluation of some strings.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.5.4
references:
- type: WEB
  url: https://groups.google.com/forum/#!searchin/ansible-project/1.5.4/ansible-project/MUQxiKwSQDc/id6aVaawVboJ
aliases:
- CVE-2014-2686
modified: "2020-01-21T16:01:00Z"
published: "2020-01-09T13:15:00Z"
