id: PYSEC-0000-CVE-2014-4659
package:
  name: ansible
  ecosystem: PyPI
details: Ansible before 1.5.5 sets 0644 permissions for sources.list, which might
  allow local users to obtain sensitive credential information in opportunistic circumstances
  by reading a file that uses the "deb http://user:pass@server:port/" format.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 1.5.5
references:
- type: WEB
  url: https://www.securityfocus.com/bid/68234
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
aliases:
- CVE-2014-4659
modified: "2020-02-25T21:00:00Z"
published: "2020-02-20T15:15:00Z"
