id: PYSEC-0000-CVE-2014-4967
package:
  name: ansible
  ecosystem: PyPI
details: Multiple argument injection vulnerabilities in Ansible before 1.6.7 allow
  remote attackers to execute arbitrary code by leveraging access to an Ansible managed
  host and providing a crafted fact, as demonstrated by a fact with (1) a trailing
  " src=" clause, (2) a trailing " temp=" clause, or (3) a trailing " validate=" clause
  accompanied by a shell command.
affects:
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    fixed: 62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
  - type: ECOSYSTEM
    fixed: 1.6.7
references:
- type: WEB
  url: https://github.com/ansible/ansible/commit/62a1295a3e08cb6c3e9f1b2a1e6e5dcaeab32527
- type: WEB
  url: http://www.ocert.org/advisories/ocert-2014-004.html
aliases:
- CVE-2014-4967
modified: "2020-02-26T15:35:00Z"
published: "2020-02-18T15:15:00Z"
