id: PYSEC-0000-CVE-2018-10875
package:
  name: ansible
  ecosystem: PyPI
details: A flaw was found in ansible. ansible.cfg is read from the current working
  directory which can be altered to make it point to a plugin or a module path under
  the control of an attacker, thus allowing the attacker to execute arbitrary code.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: "2.5"
    fixed: 2.5.6
  - type: ECOSYSTEM
    introduced: "2.4"
    fixed: 2.4.6.0
  - type: ECOSYSTEM
    introduced: "2.6"
    fixed: 2.6.1
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10875
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2166
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2152
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2151
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2150
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2321
- type: WEB
  url: http://www.securitytracker.com/id/1041396
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2585
- type: WEB
  url: https://access.redhat.com/errata/RHBA-2018:3788
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:0054
- type: WEB
  url: https://www.debian.org/security/2019/dsa-4396
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html
- type: WEB
  url: https://usn.ubuntu.com/4072-1/
- type: WEB
  url: https://lists.debian.org/debian-lts-announce/2019/09/msg00016.html
aliases:
- CVE-2018-10875
modified: "2020-05-29T18:20:00Z"
published: "2018-07-13T22:29:00Z"
