id: PYSEC-0000-CVE-2019-14905
package:
  name: ansible
  ecosystem: PyPI
details: A vulnerability was found in Ansible Engine versions 2.9.x before 2.9.3,
  2.8.x before 2.8.8, 2.7.x before 2.7.16 and earlier, where in Ansible's nxos_file_copy
  module can be used to copy files to a flash or bootflash on NXOS devices. Malicious
  code could craft the filename parameter to perform OS command injections. This could
  result in a loss of confidentiality of the system among other issues.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: 2.7.0
    fixed: 2.7.16
  - type: ECOSYSTEM
    introduced: 2.8.0
    fixed: 2.8.8
  - type: ECOSYSTEM
    introduced: 2.9.0
    fixed: 2.9.3
references:
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2020:0218
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2020:0216
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5BNCYPQ4BY5QHBCJOAOPANB5FHATW2BR/
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14905
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00021.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00026.html
aliases:
- CVE-2019-14905
modified: "2020-04-16T19:15:00Z"
published: "2020-03-31T17:15:00Z"
