steps:
  - id: Lock
    name: golang:1.17.3
    entrypoint: bash
    args:
      - -ec
      - |
        if [[ "$COMMIT_SHA" = '' ]]; then
          echo "no COMMIT_SHA, not locking"
          exit 0
        fi
        go run golang.org/x/website/cmd/locktrigger@latest \
          -project $PROJECT_ID -build $BUILD_ID -repo https://go.googlesource.com/vulndb

  - id: Unshallow
    name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        if ! git fetch --unshallow; then
          echo "git fetch --unshallow failed, no worries mate"
        fi

  - id: Generate
    name: golang
    entrypoint: bash
    args: ["-c", "go run ./cmd/gendb -out /workspace/db"]

  - id: Deploy
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: ["./deploy/gcp-deploy.sh"]
