steps:
  - id: Lock
    name: golang:1.17.3
    entrypoint: bash
    args:
      - -ec
      - |
        if [[ "$COMMIT_SHA" = '' ]]; then
          echo "no COMMIT_SHA, not locking"
          exit 0
        fi
        go run golang.org/x/website/cmd/locktrigger@latest \
          -project $PROJECT_ID -build $BUILD_ID -repo https://go.googlesource.com/vulndb

  - id: Unshallow
    name: gcr.io/cloud-builders/git
    args: ["fetch", "--unshallow"]

  - id: Generate
    name: golang
    entrypoint: bash
    args: ["-c", "go install golang.org/x/vulndb/cmd/gendb@latest
                  && gendb -out /workspace/db"]

  - id: Deploy
    name: gcr.io/cloud-builders/gsutil
    entrypoint: bash
    args: ["./deploy/gcp-deploy.sh"]
