name: CVEs On Demand

on:
  issues:
    types: [created, edited, labeled]

jobs:
  execute-cvelab-workflow:
    if: ${{ github.event.label.name == 'On-Demand' }}
    runs-on: ubuntu-latest
    steps:

    - name: Check Out
      uses: actions/checkout@main

    - name: Replace Variables
      run: |
        cat config-template.yaml | sed 's/$CVE/${{ github.event.issue.title }}/g' | sed 's/$ISSUE_ID/${{ github.event.issue.number }}/g' > config.yaml

    - name: CVELab Execute
      id: cvelab
      uses: cvelab/action@main
      env:
        TRICKEST_TOKEN: "${{ secrets.TRICKEST_TOKEN }}"
      with:
        workflow: "CVE - On Demand"
        space: "CVEs"
        watch: true
        config_path: config.yaml
